server:
  servlet:
    context-path: "/app"
  port: 8080

spring:
  application:
    name: app
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: "sa"
    password: "password"
#    continueOnError: true
#    initialize: true
#    initialSize: 0
#    timeBetweenEvictionRunsMillis: 5000
#    minEvictableIdleTimeMillis: 5000
#    minIdle: 0
  h2:
    console:
      enabled: true
    settings.trace : true
    settings.web-allow-others : true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    database-platform : org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
#    properties:
#      hibernate:
#        format_sql : true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        hbm2ddl:
#          auto: none
#        temp:
#          use_jdbc_metadata_defaults: false
  logging:
    level:
      root: DEBUG
